In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('train.csv', encoding='ISO-8859-1') 

In [3]:
df

ItemID  Sentiment                                      SentimentText
0           1          0                       is so sad for my APL frie...
1           2          0                     I missed the New Moon trail...
2           3          1                            omg its already 7:30 :O
3           4          0            .. Omgaga. Im sooo  im gunna CRy. I'...
4           5          0           i think mi bf is cheating on me!!!   ...
...       ...        ...                                                ...
99984   99996          0  @Cupcake  seems like a repeating problem   hop...
99985   99997          1  @cupcake__ arrrr we both replied to each other...
99986   99998          0                     @CuPcAkE_2120 ya i thought so 
99987   99999          1  @Cupcake_Dollie Yes. Yes. I'm glad you had mor...
99988  100000          1                    @cupcake_kayla haha yes you do 

[99989 rows x 3 columns]

In [4]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer

In [5]:
type(df['SentimentText'])

pandas.core.series.Series

In [6]:
df.loc[0]

ItemID                                                           1
Sentiment                                                        0
SentimentText                         is so sad for my APL frie...
Name: 0, dtype: object

In [7]:
import re

In [8]:
  def preprocessor(text):
    text = re.sub('<[^>]*>', '', text)
    emoticons = re.findall('(?::|;|=)(?:-)?(?:\)|\(|D|P)', text)
    text = re.sub('[\W]+', ' ', text.lower()) +\
        ' '.join(emoticons).replace('-', '')
    return text

In [9]:
df['SentimentText']=df['SentimentText'].apply(preprocessor)

In [10]:
df

ItemID  Sentiment                                      SentimentText
0           1          0                       is so sad for my apl friend 
1           2          0                     i missed the new moon trailer 
2           3          1                             omg its already 7 30 o
3           4          0   omgaga im sooo im gunna cry i ve been at this...
4           5          0                i think mi bf is cheating on me t_t
...       ...        ...                                                ...
99984   99996          0   cupcake seems like a repeating problem hope y...
99985   99997          1   cupcake__ arrrr we both replied to each other...
99986   99998          0                      cupcake_2120 ya i thought so 
99987   99999          1   cupcake_dollie yes yes i m glad you had more ...
99988  100000          1                     cupcake_kayla haha yes you do 

[99989 rows x 3 columns]

In [11]:
from nltk.stem.porter import PorterStemmer

porter=PorterStemmer()

In [12]:
def tokinizer(text):
    return text.split()

In [13]:
def tokinizer_porter(text):
    return [porter.stem(word) for word in text.split()]

In [14]:
tokinizer('my name is modem naveen')

['my', 'name', 'is', 'modem', 'naveen']

In [15]:
tokinizer_porter('running is run so runner runs')

['run', 'is', 'run', 'so', 'runner', 'run']

In [16]:
import nltk

In [17]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Naveen\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [18]:
from nltk.corpus import stopwords

In [19]:
stop=stopwords.words('english')

In [20]:
stop

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [21]:
df

ItemID  Sentiment                                      SentimentText
0           1          0                       is so sad for my apl friend 
1           2          0                     i missed the new moon trailer 
2           3          1                             omg its already 7 30 o
3           4          0   omgaga im sooo im gunna cry i ve been at this...
4           5          0                i think mi bf is cheating on me t_t
...       ...        ...                                                ...
99984   99996          0   cupcake seems like a repeating problem hope y...
99985   99997          1   cupcake__ arrrr we both replied to each other...
99986   99998          0                      cupcake_2120 ya i thought so 
99987   99999          1   cupcake_dollie yes yes i m glad you had more ...
99988  100000          1                     cupcake_kayla haha yes you do 

[99989 rows x 3 columns]

In [22]:
df=df.drop('ItemID',axis=1)

In [23]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [24]:
tfidf=TfidfVectorizer(strip_accents=None,lowercase=False,preprocessor=None,tokenizer=tokinizer_porter,use_idf=True,norm='l2',smooth_idf=True)

In [25]:
y=df.Sentiment.values

In [26]:
y

array([0, 0, 1, ..., 0, 1, 1], dtype=int64)

In [27]:
X=tfidf.fit_transform(df.SentimentText)

In [28]:
X[0][0:30]

<1x95362 sparse matrix of type '<class 'numpy.float64'>'
	with 7 stored elements in Compressed Sparse Row format>

In [29]:
from sklearn.model_selection import train_test_split

In [30]:
X_train,X_test,Y_train,Y_test=train_test_split(X,y,test_size=0.3)

In [31]:
import pickle

In [32]:
from sklearn.linear_model import LogisticRegressionCV

In [33]:
clf=LogisticRegressionCV(cv=5,scoring='accuracy',n_jobs=-1,random_state=0,verbose=3,max_iter=300).fit(X_train,Y_train)

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done   2 out of   5 | elapsed:  1.6min remaining:  2.4min
[Parallel(n_jobs=-1)]: Done   5 out of   5 | elapsed:  1.7min finished


In [38]:
saved_model=open('savedmodel.sav','wb')

In [39]:
pickle.dump(clf,saved_model)

In [44]:
clf.score(X_test,Y_test)

0.7751108444177751

In [45]:
clf.score(X_train,Y_train)

0.8798434106755058

In [46]:
Y_pred=clf.predict(X_test)

In [47]:
from sklearn.metrics import confusion_matrix
confusion=confusion_matrix(Y_test,Y_pred)

In [48]:
confusion

array([[ 9095,  3830],
       [ 2916, 14156]], dtype=int64)

In [166]:
X=['PM @narendramodi has spoken to Andhra Pradesh CM Shri @ysjagan regarding the situation in Visakhapatnam. He assured all help and support.','I love my college','First half is boring and second half changed my opinion totally','I am sad','I am not sad']

In [167]:
X=tfidf.transform(X)

In [168]:
Y_pred=clf.predict(X)

In [169]:
Y_pred

array([1, 1, 0, 0, 0], dtype=int64)

In [45]:
from sklearn.naive_bayes import MultinomialNB
nb=MultinomialNB()

In [46]:
nb.fit(X_train,Y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [47]:
nb.score(X_test,Y_test)

0.7378737873787379

In [48]:
nb.score(X_train,Y_train)

0.862369985141159

In [49]:
pred_nb=nb.predict(X_test)
confusion=confusion_matrix(Y_test,pred_nb)

In [50]:
print(confusion)

[[ 7056  6015]
 [ 1848 15078]]


In [51]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()
rf.fit(X_train,Y_train)
print(rf.score(X_test,Y_test))

0.7601426809347601


In [57]:
newtweet=['Its a  bad experirnce guys']

In [58]:
x_tes=tfidf.transform(newtweet)

In [62]:
x_tes

<1x5 sparse matrix of type '<class 'numpy.float64'>'
	with 5 stored elements in Compressed Sparse Row format>

In [72]:
# type(X_test)

scipy.sparse.csr.csr_matrix

In [73]:
# X_test_df=pd.DataFrame(X_test.toarray())

In [75]:
X_test_df[0]

0        0.0
1        0.0
2        0.0
3        0.0
4        0.0
        ... 
29992    0.0
29993    0.0
29994    0.0
29995    0.0
29996    0.0
Name: 0, Length: 29997, dtype: float64

In [77]:
# a=CountVectorizer()
# a.fit(df['SentimentText'])

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [78]:
# print(a.vocabulary_)

{'is': 71938, 'so': 93674, 'sad': 90542, 'for': 65062, 'my': 80817, 'apl': 21665, 'friend': 65503, 'missed': 79478, 'the': 97552, 'new': 81633, 'moon': 80032, 'trailer': 99049, 'omg': 83232, 'its': 72089, 'already': 14693, '30': 1718, 'omgaga': 83233, 'im': 70919, 'sooo': 93951, 'gunna': 67860, 'cry': 57814, 've': 101379, 'been': 31808, 'at': 25403, 'this': 97908, 'dentist': 59550, 'since': 92847, '11': 279, 'was': 102394, 'suposed': 96026, 'just': 73528, 'get': 66440, 'crown': 57664, 'put': 87411, 'on': 83282, '30mins': 1754, 'think': 97880, 'mi': 79029, 'bf': 33599, 'cheating': 48348, 'me': 78448, 't_t': 96554, 'or': 83552, 'worry': 103928, 'too': 98750, 'much': 80504, 'juuuuuuuuuuuuuuuuussssst': 73586, 'chillin': 49562, 'sunny': 95932, 'again': 9686, 'work': 103863, 'tomorrow': 98680, 'tv': 99723, 'tonight': 98722, 'handed': 68325, 'in': 71113, 'uniform': 100724, 'today': 98559, 'miss': 79465, 'you': 104998, 'hmmmm': 69534, 'wonder': 103723, 'how': 70048, 'she': 92122, 'number': 825

In [79]:
# from sklearn.feature_extraction.text import TfidfTransformer

In [81]:
# b=TfidfTransformer(use_idf=True,norm='l2',smooth_idf=True)

In [85]:
# f=b.fit_transform(a.fit_transform(df['SentimentText']))

In [6]:
data=[]

In [12]:
for i in df['SentimentText'][0:1000]:
    data.append(i)

In [14]:
vectorizer = CountVectorizer(
    analyzer = 'word',
    lowercase = True,
)
features = vectorizer.fit_transform(
    data
)
features_nd = features.toarray() # for easy usage

MemoryError: Unable to allocate 130. GiB for an array with shape (164989, 105849) and data type int64